### PR TITLE
chore: release v4.2.1

### PR DESCRIPTION
**Pull request by michael-siek**

### CODE REVIEW

**Comment by michael-siek** [comment]
# Release Audit 
- [x] https://github.com/dequelabs/axe-core-gems/pull/189
- [x] https://github.com/dequelabs/axe-core-gems/pull/192

**Review by AdnoC — DISMISSED** [review]

**Comment by dylanb** [comment]
reviewed

**Review by WilcoFiers — APPROVED** [review]
## Release Audit
- [ ] https://github.com/dequelabs/axe-core-gems/pull/189 Feels like this should have been "chore"
- [x] https://github.com/dequelabs/axe-core-gems/pull/192

**Comment by dylanb** [comment]
reviewed

**Pull request merged**
