### PR TITLE
chore: release v4.4.1

### PR DESCRIPTION
**Pull request by Grandmagic13**
<< Describe the changes >>

Closes issue: #<< ticket number >>

### CODE REVIEW

**Comment by Grandmagic13** [comment]
@stephenmathieson @scurker @schne324 @michael-siek Would you kindly review? Thank you in advance.

**Comment by michael-siek** [comment]
# Release Audit v4.4.1
- [x] https://github.com/dequelabs/axe-core-gems/pull/232
- [x] https://github.com/dequelabs/axe-core-gems/pull/237
- [x] https://github.com/dequelabs/axe-core-gems/pull/231

**Comment by michael-siek** [comment]
Thank you for your contribution @Grandmagic13!

**Review by michael-siek — APPROVED** [review]

**Comment by keith-rhodes-0723** [comment]
reviewed

**Pull request merged**
